### ISSUE TITLE
Url normalization

### ISSUE THREAD

**Issue by gsouf** [serp-scrape/serps#15]
As talked in #14 it would be useful to have url normalization as described here: https://tools.ietf.org/html/rfc3986#section-6.2.2

The following resources look perfect for that: 
- http://sabre.io/uri/usage/ (in this case, it will also serve for resolving uri)
- https://github.com/glenscott/url-normalizer (simpler, just providing uri normalization)

@RubtsovAV You were talking about zend uri, but I told that using a full uri abstraction library had too many drawbacks and limitations for SERPS. Please check at [sabre/uri](http://sabre.io/uri/usage/), it does not provide a full uri implementation, instead it gives some tools to manipulate uri. Looks perfect for that.

**Comment by TechAlchemistry** [comment]
I'm not sure understand you want. You have decided to replace the URL class?

**Comment by gsouf** [comment]
Not replacing, that's an addition to make its management easier

**Comment by TechAlchemistry** [comment]
Or you want to copy of some parts from this class? The method `removeDotSegment()`? Or you want full normalize from that class?

**Comment by gsouf** [comment]
I will probably add it as a dependency

**Comment by TechAlchemistry** [comment]
So, and what about the test suite?

**Comment by gsouf** [comment]
What's the relation ?

**Comment by TechAlchemistry** [comment]
Will we need the test from PR https://github.com/serp-spider/core/pull/14 ?

**Comment by gsouf** [comment]
Yes tests from #14 will be needed to make sure everything is fine, but most of the implementation you proposed will be replaced by this

**Comment by TechAlchemistry** [comment]
And we will need to the split it test on two: resolve and normalize, right?

**Comment by gsouf** [comment]
Yes, exactly!

**Comment by gsouf** [comment]
Well, after analysing how `sabre/uri::normalize` works, it will be lighter in term of performances to extract the code from it to integrate it in serps. The reason is `sabre/uri::normalize` parses the uri in an array of items, then it normalizes each part, then it build back the url into a string. SERPS actually only needs the intermediate part (normalizing) because everything is already split in parts, and we need to parse it again after, making double processing for the final output

**Comment by gsouf** [comment]
sabre/uri also removes .. and . when resolving uri

**Comment by TechAlchemistry** [comment]
And I think be better if we remove the second argument of the resolve method and place it behavior in the method buildUrl. How you think?

**Comment by gsouf** [comment]
That's an other story, but no, because resolve is intensively used internally, and it's here for performance purposes

**Comment by TechAlchemistry** [comment]
It's strange, because this not provide performance benefits. This method is now performs double work and it would be logical to bring the behavior to a more appropriate place for this.

**Comment by TechAlchemistry** [comment]
Besides, you said it was no problem to change the behavior of the method, because library yet not released.

**Comment by gsouf** [comment]
I didnt place it by accident, believe me (and as i said, it's not the same topic as the issue's)

**Comment by gsouf** [comment]
Implemented in master for v0.2.0
