### ISSUE TITLE
class_implements(): Class string does not exist and could not be loaded

### ISSUE THREAD

**Issue by lmahesh5** [serp-scrape/serps#24]
Hi @gsouf 
Three days back we did the pull for latest code.
For last 3 days, we are getting one error in urlarchivetrait while calling this function : $response->getNaturalResults();

It throws the error 
ErrorException in UrlArchiveTrait.php line 322:
class_implements(): Class string does not exist and could not be loaded

Are you not facing this error or in the last 3 days did you do some changes which fixes this?

**Comment by gsouf** [comment]
Hi @lmahesh5 

Yes that should be fixed in master, but you have to know that other breaking changes will come in master until version 0.2 is released.

Can you update your deps and let me know if it's ok please?

**Comment by lmahesh5** [comment]
@gsouf 

Can you please let us know the breaking changes in master version.
If the changes are less and doable in short time, then we can go for that.

Otherwise we have to think of the second option.

**Comment by gsouf** [comment]
It seems that changelogs for unreleased version are not visible. For google repository I created a public file for global [changelogs](https://github.com/serp-spider/search-engine-google/blob/master/CHANGELOG.md) including master. I will do the same with core repo

**Comment by gsouf** [comment]
Core changelogs are available: https://github.com/serp-spider/core/blob/master/CHANGELOG.md
