### ISSUE TITLE
Uninitialized string offset: 1 in UrlArchiveTrait.php

### ISSUE THREAD

**Issue by huglester** [serp-scrape/serps#27]
Hello,

I sometimes get this error:

PHP Notice:  Uninitialized string offset: 1 in ./spider/vendor/serps/core/src/Core/Url/UrlArchiveTrait.php on line 208

**Comment by gsouf** [comment]
Hi @huglester 

Thanks for the repport, I will try to reproduce and fix the issue

**Comment by gsouf** [comment]
@huglester  it's fixed in version 0.1.3 of core, thanks for the repport
