### ISSUE TITLE
Just installed and configure Call to undefined method Serps\Core\Serp\ItemPosition::getType()

### ISSUE THREAD

**Issue by Chitzi** [serp-scrape/serps#28]
As the example in README.

Uncaught Error: Call to undefined method Serps\Core\Serp\ItemPosition::getType()

**Comment by gsouf** [comment]
Hi @Chitzi 

You are right the Readme is wrong and refers to an older unavailable method. The correct method is to use ``getTypes`` that will return an array of types or ``is``. You have the full details here:

http://serp-spider.github.io/documentation/search-engine/google/parse-page/#natural-results


Thanks for repporting
