### ISSUE TITLE
Error: Catchable fatal error: Argument 1 passed to Serps\SearchEngine\Google\GoogleClient::__construct() must be an instance of Serps\Core\Browser\BrowserInterface, instance of Serps\HttpClient\CurlClient given

### ISSUE THREAD

**Issue by mozgbrasil** [serp-scrape/serps#33]
Hello good afternoon

    Error: Catchable fatal error: Argument 1 passed to Serps\SearchEngine\Google\GoogleClient::__construct() must be an instance of Serps\Core\Browser\BrowserInterface, instance of Serps\HttpClient\CurlClient given

1. 

Following the example you provided in

https://serp-spider.github.io/documentation/overview/

If I use the following script

    use Serps\SearchEngine\Google\GoogleClient;
    use Serps\HttpClient\CurlClient;

    $googleUrl = 'https://www.google.com.br/';
    $proxy = '';

    $googleClient = new GoogleClient(new CurlClient());

    $googleClient->query($googleUrl, $proxy);

    dump($googleClient);

and the following error is returned

    Catchable fatal error: Argument 1 passed to Serps\SearchEngine\Google\GoogleClient::__construct() must be an instance of Serps\Core\Browser\BrowserInterface, instance of Serps\HttpClient\CurlClient given, called in /home/marcio/dados/public_html/git/manual/google-appengine/index.php on line 20 and defined in /home/marcio/dados/public_html/git/manual/google-appengine/vendor/serps/search-engine-google/src/GoogleClient.php on line 33

2. 

If I use the following script

    use Serps\SearchEngine\Google\GoogleClient;
    use Serps\HttpClient\CurlClient;

    $googleUrl = 'https://www.google.com.br/';
    $proxy = '';

    $googleClient = new GoogleClient();

    $googleClient->query($googleUrl, $proxy);

    dump($googleClient);

the following error is returned

    Catchable fatal error: Argument 1 passed to Serps\SearchEngine\Google\GoogleClient::query() must be an instance of Serps\SearchEngine\Google\GoogleUrlInterface, string given, called in /home/marcio/dados/public_html/git/manual/google-appengine/index.php on line 22 and defined in /home/marcio/dados/public_html/git/manual/google-appengine/vendor/serps/search-engine-google/src/GoogleClient.php on line 48

**Comment by mozgbrasil** [comment]
I was able to do the simulation based on the following example

https://serp-spider.github.io/documentation/search-engine/google/

**Comment by gsouf** [comment]
Hi @mozgbrasil 

Indeed the intructions on the first  link are outdated. I re-open the issue until I fix it.

Thanks for figuring the out this issue.

**Comment by gsouf** [comment]
Documentation is now fixed.
